force-app/main/default/objects/Krow_Project__c/Krow_Project__c.object-meta.xml
<CustomObject>
    <label>Krow Project</label>
    <nameField>
        <displayFormat>K-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Krow Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow_Project__c/fields/isTemplateKrow__c.field-meta.xml
<CustomField>
    <fullName>isTemplateKrow__c</fullName>
    <formula>ISPICKVAL( Onboarding_Type__c , &apos;Template&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isTemplateKrow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Krow_Project__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Krow Projects</relationshipLabel>
    <relationshipName>Krow_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Krow_Task__c/Krow_Task__c.object-meta.xml
<CustomObject>
    <label>Krow Task</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Krow Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderHelper.cls
public class OrderHelper {
    public static void beforeUpdate(List<Order> orList, Map<Id,Order> newMap,Map<Id,Order> oldMap){
        Set<Id> orderId = new Set<Id>();
        List<Krow_Project__c> kpList = new List<Krow_Project__c>();
        for (Order orObj : orList){
            if(orObj.OpportunityId != null){
                if(oldMap.get(orObj.id).Status != 'Complete' && newMap.get(orObj.Id).Status == 'Complete' && orObj.Opportunity.StageName == 'Signature'){
                    Krow_Project__c krpObj = new Krow_Project__c();
                   	krpObj.Onboarding_Type__c = 'Installation';
                    krpObj.OrderId__c = orObj.Id;
                    kpList.add(krpObj);
                    
                }
            }else{
                orObj.addError('Cannot Change Status to Complete as linked opprtunity stage is not Signature.');
            }
            
        }
        if(!kpList.isEmpty()){
            insert kpList;
        }
        List<Krow_Task__c> ktTaskList = [Select id  from Krow_Task__c WHere Krow_Project__r.isTemplateKrow__c = true];
       
        List<Krow_Task__c> clonedList = new List<Krow_Task__c>();
        for (Krow_Project__c kpObj : kpList){
            for (Krow_Task__c ktObj : ktTaskList){
                Krow_Task__c clonedTask = ktObj.Clone(true,true,false,false);
                clonedTask.Id = null;
                clonedTask.Krow_Project__c = kpObj.Id;
                clonedList.add(clonedTask);
            }
            
        }
        if(!clonedList.isEmpty()){
            insert clonedList;
        }
    }
    
}