force-app/main/default/objects/Voucher__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Gu_Id__c.field-meta.xml
<CustomField>
    <fullName>Gu_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Gu_Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/PartyName__c.field-meta.xml
<CustomField>
    <fullName>PartyName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PartyName</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/VoucherType__c.field-meta.xml
<CustomField>
    <fullName>VoucherType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>VoucherType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TallyBatch.cls
public with sharing class  TallyBatch implements Database.Batchable <SObject>,schedulable {
    //START METHOD
    public Database.QueryLocator start(Database.BatchableContext bc){
        String query= 'Select Id,Amount__c,VoucherNumber__c,PartyName__c,VoucherType__c,Quantity__c,Company_Name__c,Gu_Id__c from Voucher__c where Process__c = \'Unprocessed\'';
        return Database.getQueryLocator(Query);
    }
    //EXECUTE METHOD
    public void execute(Database.BatchableContext bc, List<Voucher__c> scopeList){
        HandleAccount.handleParentAccount(scopeList);
        HandleAccount.handleChildAccount(scopeList);
        handleOrder.handleOrderchange(scopeList);
        
        
    }
    //FINISH METHOD 
    public void finish(Database.BatchableContext bc){
        
    }
    public void execute(SchedulableContext sc){
        TallyBatch oppAssessmentUpdate = new TallyBatch();
        database.executeBatch(oppAssessmentUpdate,200);
    }
    
}