force-app/main/default/objects/Voucher__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Gu_Id__c.field-meta.xml
<CustomField>
    <fullName>Gu_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Gu_Id</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/PartyName__c.field-meta.xml
<CustomField>
    <fullName>PartyName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PartyName</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/VoucherType__c.field-meta.xml
<CustomField>
    <fullName>VoucherType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>VoucherType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountHandle.cls
public class AccountHandle {
    @AuraEnabled
    public static list<Voucher__c> readCSVFile(Id idContentDocument){
        
        List<Voucher__c> Vclist = new list<Voucher__c>();///new
        
        if(idContentDocument != null) {
            // getting File Data based on document id 
            ContentVersion objVersion = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:idContentDocument];
            // split the file data
            list<String> lstCSVLines = objVersion.VersionData.toString().split('\n');
            for(Integer i = 1; i < lstCSVLines.size(); i++){
                Voucher__c vc = new Voucher__c();
                list<String> csvRowData = lstCSVLines[i].split(',');
                System.debug('csvRowData====> '+csvRowData);
                vc.Company_Name__c = csvRowData[0];
                vc.PartyName__c = csvRowData[1];
                vc.VoucherNumber__c = 11;  //csvRowData[2];
                vc.VoucherType__c=csvRowData[3];               
                vc.Amount__c = 22; //csvRowData[4]; 
                vc.Quantity__c= 23; //csvRowData[5];
                vc.Gu_Id__c=csvRowData[6];
                Vclist.add(vc);
                system.debug('Vclist'+Vclist);
            }
        } 
        return Vclist;    
    }
    
    @AuraEnabled
    public static void insertCSVFile(list<Voucher__c> accList){
        system.debug('accList'+accList);
        try{    
            if(!accList.isEmpty()) {
                HandleAccount.handleParentAccount(accList);
                HandleAccount.handleChildAccount(accList);
                handleOrder.handleOrderchange(accList);
            }
        }
        catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }     
    }
    
    
    @AuraEnabled
    public static void documentIdapx(Id idContentDocument){
        system.debug('idContentDocument'+idContentDocument);
        List<contentdocument> clist =[SELECT Id FROM contentdocument WHERE Id =:idContentDocument ];
        system.debug('clist'+clist);
        delete clist;
    }
    
}