force-app/main/default/objects/Account/fields/Number_of_campaign__c.field-meta.xml
<CustomField>
    <fullName>Number_of_campaign__c</fullName>
    <label>Number of campaign</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_campaign_members__c.field-meta.xml
<CustomField>
    <fullName>Number_of_campaign_members__c</fullName>
    <label>Number of campaign members</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignMemberTest.cls
@isTest
public class CampaignMemberTest {
    @isTest public static void afterupdateContactWithAccount(){
        Integer NumberOfCampaign = 1;
        Integer NumberOfAccount = 1;
        Integer NumberOfContact = 2;
        TestDataFactory.CampaignData(NumberOfCampaign, NumberOfAccount, NumberOfContact);
        List<Account> accList = [Select id,Number_of_campaign__c,Number_of_campaign_members__c From Account];
        for (Account accObj : accList){
            System.assertEquals(NumberOfContact, accObj.Number_of_campaign_members__c);
            System.assertEquals(NumberOfCampaign, accObj.Number_of_campaign__c);
        }
    }
    @isTest public static void AccountContactInMultipleCampaigns(){
        Integer NumberOfCampaign = 2;
        Integer NumberOfAccount = 1;
        Integer NumberOfContact = 2;
        TestDataFactory.CampaignData(NumberOfCampaign, NumberOfAccount, NumberOfContact);
        List<Account> accList = [Select id,Number_of_campaign__c,Number_of_campaign_members__c From Account];
        for (Account accObj : accList){
            System.assertEquals(NumberOfContact, accObj.Number_of_campaign_members__c);
            System.assertEquals(NumberOfCampaign, accObj.Number_of_campaign__c);
        }
        
    }
    
    
    
}